%% Load the model specific parameters
%% 
name = 'ElasRBC_Short_Pr4_2_Time0_75s';

%% Reference parameters 
ReferenceParameters

%% Description of the tube model
% The vessel boundary is partitioned into the inlet, outlet and sidewall 
% in order to assign the Dirichlet and Neumann boundary conditions on the 
% relevant part of the boundaries. 
% The extracellular plasma flow is generated by imposing the pressure 
% gradient along the vessel length by applying a prescribed pressure on the
% inlet surface and setting the outlet surface to be the traction-free 
% surface (zero-pressure). These traction boundary conditions on the inlet 
% and outlet surfaces are referred to as the Neumann boundary conditions. 
% The zero-velocity field (no-slip condition) is assumed on the vessel 
% sidewall which amounts to the Dirichlet boundary condition. 

%% Load mesh
%% Vessel models
load ShortMicrocapillary_16El.mat

%% Parameters 
%% Fluid properties
%% Viscosity of exterior fluid
mu_out = 1.2*10^(-3); % Pa.s 
mu = mu_out/RefViscosity; 
%% Viscosity of interior fluid
mu_in = 6*10^(-3); % Pa.s
lam = mu_in/RefViscosity; % lam*mu

%% Shell properties
%% Material properties 
ShearModulus = 5.3*10^(-6); % N/m
ES = ShearModulus/RefElasticModulus; % inplane shear modulus
BendingModulus = 2*10^(-19); % N.m
EB = BendingModulus/RefBendingModulus; % bending modulus
DilatationModulus = 50*ShearModulus; % N/m
ED = DilatationModulus/RefElasticModulus; % inplane dilatational modulus